### ISSUE TITLE
errors from the simulations

### ISSUE THREAD

**Issue by marcellastro** [MarcoVelliscig/ESD_profiles#2]
I do not understand the errors from the simulations. If I look at the compute_chi_squared (line ~430), 
it seems that you assign the error on the simulations by doing 
(self.ESD_84th_error[ibin][sub_type_tag][min_index]  - \
 self.ESD_16th_error[ibin][sub_type_tag][min_index])/2
which is fine in theory but this number is sometimes NEGATIVE (see the end of the message).
How can that be?
#1 bin R ESD ESD_84 ESD_16 ESD_84-ESD_16

1 0.0255025159568 81.8239345625 10.5711578 10.6707515769 -0.0995937768941
1 0.040365062654 56.4937537519 8.99295541179 8.22209966608 0.770855745708
1 0.0638893097639 34.3780908475 6.47122884317 6.04700299401 0.424225849156
1 0.101123198867 20.3900058318 5.36099965493 5.03191459198 0.329085062952
1 0.165811121464 12.0496463087 3.45573431934 3.55655369917 -0.100819379832
1 0.262443751097 8.58004667681 3.13159439923 2.69352997565 0.438064423572
1 0.415392667055 3.88714403818 1.74453448759 1.6414753973 0.103059090294
1 0.65747833252 2.95318940463 1.08090004556 1.13967439853 -0.0587743529681
1 1.04064822197 1.12630773979 0.537635954134 0.551572860351 -0.0139369062173
1 1.64712500572 0.593715465094 0.500084473445 0.478312030314 0.0217724431313
2 0.0255025159568 95.683912561 11.6545924721 10.858071162 0.796521310074
2 0.040365062654 63.5543561396 10.3460568566 9.62251808636 0.723538770243
2 0.0638893097639 39.678308941 8.3693592066 7.86195000148 0.507409205125
2 0.101123198867 27.3395703307 6.85101848381 7.19155682941 -0.340538345602
2 0.165811121464 19.4800038992 5.79229028981 5.49712779496 0.29516249485
2 0.262443751097 15.3686977111 3.96871121068 4.00364414998 -0.0349329392978
2 0.415392667055 10.5164024442 2.98728114746 2.65194952737 0.335331620096
2 0.65747833252 6.8937819664 1.34470878871 1.39964549476 -0.0549367060566
2 1.04064822197 3.89032674409 1.11381951897 0.981410764846 0.132408754124
2 1.64712500572 1.66502621612 1.04743399918 1.4753291661 -0.427895166919
3 0.0255025159568 153.559387745 16.8244161691 15.92920967 0.895206499137
3 0.040365062654 101.951784481 13.7559038431 15.1848738962 -1.4289700531
3 0.0638893097639 70.6612845267 11.782385578 11.6827743783 0.0996111997038
3 0.101123198867 53.2222494232 7.98062882054 6.65012817532 1.33050064522
3 0.165811121464 34.1457671245 6.05825525892 5.06259747182 0.995657787098
3 0.262443751097 22.9901300363 3.64879898758 3.60317585977 0.0456231278171
3 0.415392667055 15.8697422913 3.44396155289 2.6445546932 0.79940685969
3 0.65747833252 9.08987491529 2.82926359536 2.29831792565 0.530945669713
3 1.04064822197 5.17145401231 1.37976882176 1.08748083638 0.292287985379
3 1.64712500572 2.38047081152 0.631485665359 0.503389340524 0.128096324835
4 0.0255025159568 207.900721462 30.9969592659 35.5766102443 -4.57965097837
4 0.040365062654 144.028922417 18.3084126854 19.3388047971 -1.03039211173
4 0.0638893097639 102.936669032 13.5590489993 14.6070686369 -1.04801963758
4 0.101123198867 75.8974815387 16.324306485 12.5931300784 3.73117640657
4 0.165811121464 50.1722646622 12.5850458744 8.8757170418 3.70932883262
4 0.262443751097 34.0746770311 9.15902080239 7.01989180525 2.13912899714
4 0.415392667055 20.6882520859 5.41003828183 4.71912769252 0.690910589307
4 0.65747833252 14.6728487297 2.40062999176 2.40644141128 -0.00581141952752
4 1.04064822197 8.45716350181 1.0708621198 1.09291869094 -0.022056571131
4 1.64712500572 3.95599944708 0.732868572445 0.678775529447 0.0540930429981
5 0.0255025159568 313.195530399 23.0166737421 18.8756233464 4.14105039569
5 0.040365062654 232.120177566 18.6886001494 18.6029719211 0.0856282282217
5 0.0638893097639 175.331099812 13.9193580723 13.1362748812 0.783083191072
5 0.101123198867 126.212714216 10.7606523092 10.5251223293 0.235529979971
5 0.165811121464 92.3896047763 8.86530523236 8.58670206769 0.278603164676
5 0.262443751097 61.7028867717 6.91513099531 6.31150904633 0.603621948983
5 0.415392667055 39.7917116543 4.51409459389 4.45217087236 0.06192372153
5 0.65747833252 23.364039267 2.71823301734 2.55521952932 0.163013488022
5 1.04064822197 12.0893606962 1.61795115268 1.94260708598 -0.324655933301
5 1.64712500572 7.00162781332 1.05678786188 1.05698749675 -0.000199634872218

**Comment by MarcoVelliscig** [comment]
solved the bug!
The sigma in the chi^2 calculation was the difference between the upper and the lower error bar instead of the difference between the 84th and 16th percentile (the variable name was misleading)
